CREATE TABLE  "BLOG_TABLE" 
   (	"BLOG_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BLOG_AUTHOR" VARCHAR2(255 CHAR), 
	"BLOG_CONTENT" VARCHAR2(2500), 
	"BLOG_DATE" DATE, 
	"BLOG_IMAGE" VARCHAR2(255 CHAR), 
	"BLOG_SLUG" VARCHAR2(255 CHAR), 
	"BLOG_TITLE" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("BLOG_ID") ENABLE
   ) ;